<?php

/*
 *          M""""""""`M            dP
 *          Mmmmmm   .M            88
 *          MMMMP  .MMM  dP    dP  88  .dP   .d8888b.
 *          MMP  .MMMMM  88    88  88888"    88'  `88
 *          M' .MMMMMMM  88.  .88  88  `8b.  88.  .88
 *          M         M  `88888P'  dP   `YP  `88888P'
 *          MMMMMMMMMMM    -*-  Created by Zuko  -*-
 *
 *          * * * * * * * * * * * * * * * * * * * * *
 *          * -    - -   F.R.E.E.M.I.N.D   - -    - *
 *          * -  Copyright © 2026 (Z) Programing  - *
 *          *    -  -  All Rights Reserved  -  -    *
 *          * * * * * * * * * * * * * * * * * * * * *
 */

namespace Zuko\BitMasks\Concerns;

use Zuko\BitMasks\BitMask;
use Zuko\BitMasks\Support\FlagName;

/**
 * Helpers for int-backed enums whose cases are power-of-two flag values.
 *
 * Classes generated by `php artisan make:bitmask` use this trait, but any
 * int-backed enum can adopt it:
 *
 *   enum Network: int
 *   {
 *       use BitMaskFlags;
 *
 *       case Gmail = 1 << 0;
 *       case Yahoo = 1 << 1;
 *   }
 *
 *   Network::mask(Network::Gmail, Network::Yahoo);   // BitMask(3)
 *   Network::Gmail->in($subscriber->networks);       // bool
 */
trait BitMaskFlags
{
    /**
     * Build a {@see BitMask} (bound to this enum) from the given flags.
     */
    public static function mask(mixed ...$flags): BitMask
    {
        return BitMask::from($flags, static::class);
    }

    /**
     * An empty mask bound to this enum.
     */
    public static function none(): BitMask
    {
        return BitMask::none(static::class);
    }

    /**
     * A mask with every case of this enum set.
     */
    public static function all(): BitMask
    {
        return BitMask::all(static::class);
    }

    /**
     * The enum cases contained in the given mask.
     *
     * @return list<static>
     */
    public static function fromMask(mixed $mask): array
    {
        return BitMask::from($mask, static::class)->flags();
    }

    /**
     * The case identified by the given flag name.
     *
     * Matching is forgiving (case-insensitive, separators ignored):
     * 'gmail', 'Gmail', 'YAHOO_MAIL' and 'yahoo mail' all resolve.
     *
     * @throws \InvalidArgumentException when the name matches no case
     */
    public static function fromName(string $name): static
    {
        return FlagName::resolve(static::class, $name);
    }

    /**
     * The case identified by the given flag name, or null when none matches.
     */
    public static function tryFromName(string $name): ?static
    {
        return FlagName::tryResolve(static::class, $name);
    }

    /**
     * The integer value held by the named flag — the direct string-to-int
     * bridge for raw data work: Network::valueOf('gmail') === 1.
     *
     * @throws \InvalidArgumentException when the name matches no case
     */
    public static function valueOf(string $name): int
    {
        return static::fromName($name)->value;
    }

    /**
     * Whether this flag is present in the given mask.
     */
    public function in(mixed $mask): bool
    {
        return BitMask::from($mask)->has($this);
    }

    /**
     * Whether this flag is absent from the given mask.
     */
    public function notIn(mixed $mask): bool
    {
        return ! $this->in($mask);
    }
}
