<?php

/*
 *          M""""""""`M            dP
 *          Mmmmmm   .M            88
 *          MMMMP  .MMM  dP    dP  88  .dP   .d8888b.
 *          MMP  .MMMMM  88    88  88888"    88'  `88
 *          M' .MMMMMMM  88.  .88  88  `8b.  88.  .88
 *          M         M  `88888P'  dP   `YP  `88888P'
 *          MMMMMMMMMMM    -*-  Created by Zuko  -*-
 *
 *          * * * * * * * * * * * * * * * * * * * * *
 *          * -    - -   F.R.E.E.M.I.N.D   - -    - *
 *          * -  Copyright © 2026 (Z) Programing  - *
 *          *    -  -  All Rights Reserved  -  -    *
 *          * * * * * * * * * * * * * * * * * * * * *
 */

namespace Zuko\BitMasks\Support;

use Illuminate\Support\Str;
use InvalidArgumentException;
use Zuko\BitMasks\BitMask;

/**
 * Renders bitmask flag classes (int-backed enums or constants classes)
 * from a list of human-readable flag names.
 *
 * Pure string builder — no filesystem or framework dependency — so the
 * generation logic is unit-testable outside a Laravel app. Used by the
 * `make:bitmask` artisan command.
 */
final class BitMaskClassBuilder
{
    public const TYPE_ENUM = 'enum';

    public const TYPE_CONSTANTS = 'constants';

    /**
     * @param  list<string>  $flags  human-readable flag names, in bit order
     */
    public function __construct(
        private readonly string $class,
        private readonly string $namespace = 'App\\BitMasks',
        private readonly string $type = self::TYPE_ENUM,
        private readonly array $flags = [],
        private readonly int $startBit = 0,
    ) {
    }

    /**
     * The normalized (StudlyCase) class name that will be generated.
     */
    public function className(): string
    {
        $class = Str::studly(trim($this->class));

        if (! preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $class)) {
            throw new InvalidArgumentException(sprintf('[%s] is not a valid class name.', $this->class));
        }

        return $class;
    }

    /**
     * Render the full PHP source of the flag class.
     */
    public function build(): string
    {
        $class = $this->className();
        $namespace = $this->validatedNamespace();
        $names = $this->normalizedFlagNames();

        if ($names === []) {
            throw new InvalidArgumentException('At least one flag name is required.');
        }

        if ($this->startBit < 0 || $this->startBit > BitMask::MAX_BIT) {
            throw new InvalidArgumentException(sprintf('Start bit must be between 0 and %d.', BitMask::MAX_BIT));
        }

        $lastBit = $this->startBit + count($names) - 1;

        if ($lastBit > BitMask::MAX_BIT) {
            throw new InvalidArgumentException(sprintf(
                '%d flags starting at bit %d would exceed bit %d (the safe limit for a signed 64-bit integer). Consider splitting into multiple mask columns.',
                count($names),
                $this->startBit,
                BitMask::MAX_BIT
            ));
        }

        return match ($this->type) {
            self::TYPE_ENUM => $this->buildEnum($namespace, $class, $names),
            self::TYPE_CONSTANTS => $this->buildConstants($namespace, $class, $names),
            default => throw new InvalidArgumentException(sprintf('Unknown type [%s]. Supported types: enum, constants.', $this->type)),
        };
    }

    /**
     * @param  list<string>  $names
     */
    private function buildEnum(string $namespace, string $class, array $names): string
    {
        $cases = [];

        foreach ($names as $index => $name) {
            $cases[] = sprintf('    case %s = 1 << %d;', $name, $this->startBit + $index);
        }

        $body = implode("\n", $cases);

        return <<<PHP
<?php

namespace {$namespace};

use Zuko\BitMasks\Concerns\BitMaskFlags;

/**
 * {$class} bitmask flags.
 *
 * Generated by zuko/laravel-bit-masks (`php artisan make:bitmask`).
 */
enum {$class}: int
{
    use BitMaskFlags;

{$body}
}

PHP;
    }

    /**
     * @param  list<string>  $names
     */
    private function buildConstants(string $namespace, string $class, array $names): string
    {
        $constants = [];

        foreach ($names as $index => $name) {
            $constants[] = sprintf('    public const %s = 1 << %d;', $name, $this->startBit + $index);
        }

        $body = implode("\n\n", $constants);

        return <<<PHP
<?php

namespace {$namespace};

/**
 * {$class} bitmask flags.
 *
 * Generated by zuko/laravel-bit-masks (`php artisan make:bitmask`).
 */
final class {$class}
{
{$body}
}

PHP;
    }

    private function validatedNamespace(): string
    {
        $namespace = trim($this->namespace, '\\');

        if (! preg_match('/^[A-Za-z_][A-Za-z0-9_]*(\\\\[A-Za-z_][A-Za-z0-9_]*)*$/', $namespace)) {
            throw new InvalidArgumentException(sprintf('[%s] is not a valid namespace.', $this->namespace));
        }

        return $namespace;
    }

    /**
     * Turn human-readable flag names into valid, unique PHP identifiers —
     * StudlyCase for enum cases, SCREAMING_SNAKE for constants.
     *
     * @return list<string>
     */
    private function normalizedFlagNames(): array
    {
        $names = [];
        $seen = [];

        foreach ($this->flags as $flag) {
            $label = trim((string) $flag);

            if ($label === '') {
                continue;
            }

            $words = trim(preg_replace('/[^A-Za-z0-9]+/', ' ', $label));

            if ($words === '') {
                throw new InvalidArgumentException(sprintf('Cannot derive an identifier from flag name [%s].', $label));
            }

            $name = $this->type === self::TYPE_CONSTANTS
                ? strtoupper(Str::snake(Str::studly($words)))
                : Str::studly($words);

            if (preg_match('/^\d/', $name)) {
                $name = '_' . $name;
            }

            if (isset($seen[strtolower($name)])) {
                throw new InvalidArgumentException(sprintf('Flag name [%s] collides with another flag as identifier [%s].', $label, $name));
            }

            $seen[strtolower($name)] = true;
            $names[] = $name;
        }

        return $names;
    }
}
