<?php

/*
 *          M""""""""`M            dP
 *          Mmmmmm   .M            88
 *          MMMMP  .MMM  dP    dP  88  .dP   .d8888b.
 *          MMP  .MMMMM  88    88  88888"    88'  `88
 *          M' .MMMMMMM  88.  .88  88  `8b.  88.  .88
 *          M         M  `88888P'  dP   `YP  `88888P'
 *          MMMMMMMMMMM    -*-  Created by Zuko  -*-
 *
 *          * * * * * * * * * * * * * * * * * * * * *
 *          * -    - -   F.R.E.E.M.I.N.D   - -    - *
 *          * -  Copyright © 2026 (Z) Programing  - *
 *          *    -  -  All Rights Reserved  -  -    *
 *          * * * * * * * * * * * * * * * * * * * * *
 */

namespace Zuko\BitMasks\Support;

use BackedEnum;
use InvalidArgumentException;
use ReflectionClass;

/**
 * Resolves human-readable flag NAMES back to the flag they identify.
 *
 * Matching is forgiving: an exact case/constant name wins, otherwise the
 * lookup falls back to a normalized comparison that ignores case and
 * non-alphanumeric separators — so 'gmail', 'Gmail', 'YAHOO_MAIL',
 * 'yahoo mail' and 'yahoo-mail' all find their flag.
 *
 * Works with int-backed flag enums (the usual case) and with the constants
 * classes emitted by `make:bitmask --type=constants`:
 *
 *   FlagName::resolve(Network::class, 'gmail');   // Network::Gmail
 *   FlagName::value(Network::class, 'yahoo mail'); // 2
 */
final class FlagName
{
    /**
     * Resolve a flag name to its enum case.
     *
     * @template T of BackedEnum
     *
     * @param  class-string<T>  $enum
     * @return T
     *
     * @throws InvalidArgumentException when the name matches no case
     */
    public static function resolve(string $enum, string $name): BackedEnum
    {
        $case = self::tryResolve($enum, $name);

        if ($case === null) {
            throw new InvalidArgumentException(sprintf(
                'Unknown flag name [%s] for [%s]. Known flags: %s.',
                $name,
                $enum,
                implode(', ', array_map(static fn (BackedEnum $case) => $case->name, $enum::cases()))
            ));
        }

        return $case;
    }

    /**
     * Resolve a flag name to its enum case, or null when it matches no case.
     *
     * @template T of BackedEnum
     *
     * @param  class-string<T>  $enum
     * @return T|null
     */
    public static function tryResolve(string $enum, string $name): ?BackedEnum
    {
        if (! is_subclass_of($enum, BackedEnum::class)) {
            throw new InvalidArgumentException(sprintf('[%s] is not a backed enum.', $enum));
        }

        foreach ($enum::cases() as $case) {
            if ($case->name === $name) {
                return $case;
            }
        }

        $key = self::key($name);

        foreach ($enum::cases() as $case) {
            if (self::key($case->name) === $key) {
                return $case;
            }
        }

        return null;
    }

    /**
     * The integer value held by the named flag.
     *
     * Accepts an int-backed flag enum or a constants class (as generated by
     * `make:bitmask --type=constants`), so callers need not care which style
     * the flag class uses.
     *
     * @param  class-string  $class
     *
     * @throws InvalidArgumentException when the name matches no flag
     */
    public static function value(string $class, string $name): int
    {
        $value = self::tryValue($class, $name);

        if ($value === null) {
            throw new InvalidArgumentException(sprintf('Unknown flag name [%s] for [%s].', $name, $class));
        }

        return $value;
    }

    /**
     * The integer value held by the named flag, or null when it matches none.
     *
     * @param  class-string  $class
     */
    public static function tryValue(string $class, string $name): ?int
    {
        if (is_subclass_of($class, BackedEnum::class)) {
            $case = self::tryResolve($class, $name);

            if ($case === null) {
                return null;
            }

            if (! is_int($case->value)) {
                throw new InvalidArgumentException(sprintf('[%s] is a string-backed enum. Bitmask flags must be int-backed.', $class));
            }

            return $case->value;
        }

        if (! class_exists($class)) {
            throw new InvalidArgumentException(sprintf('[%s] is not a flag enum or constants class.', $class));
        }

        $constants = (new ReflectionClass($class))->getConstants();

        if (array_key_exists($name, $constants) && is_int($constants[$name])) {
            return $constants[$name];
        }

        $key = self::key($name);

        foreach ($constants as $constant => $value) {
            if (is_int($value) && self::key($constant) === $key) {
                return $value;
            }
        }

        return null;
    }

    /**
     * Normalized comparison key: case-insensitive, separators stripped.
     */
    private static function key(string $name): string
    {
        return strtolower((string) preg_replace('/[^A-Za-z0-9]+/', '', $name));
    }
}
